version: '3.4'

services:
  windstationapp:
    image: windstationapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
