DROP TABLE IF EXISTS dhv_sites;

CREATE TABLE dhv_sites (
    id SERIAL PRIMARY KEY,
    site_id INTEGER,
    site_name TEXT,
    site_country VARCHAR(2),
    site_type TEXT,
    site_type_en TEXT,
    height_difference_max INTEGER,
    webcam1 TEXT,
    webcam2 TEXT,
    webcam3 TEXT,
    weather_info TEXT,
    weather_phone TEXT,
    de_certified BOOLEAN,
    de_certification_holder TEXT,
    site_contact TEXT,
    site_information TEXT,
    cable_car TEXT,
    site_remarks TEXT,
    requirements TEXT,
    site_url TEXT,
    location_name TEXT,
    location_id INTEGER,
    location_type INTEGER,
    coordinates_text TEXT,
    altitude INTEGER,
    location_country VARCHAR(2),
    post_code VARCHAR(10),
    region_id INTEGER,
    region TEXT,
    municipality TEXT,
    directions TEXT,
    directions_text TEXT,
    towing_length INTEGER,
    mobile_winch INTEGER,
    towing_height1 INTEGER,
    towing_height2 INTEGER,
    access_by_car BOOLEAN,
    access_by_public_transport BOOLEAN,
    access_by_foot BOOLEAN,
    access_remarks TEXT,
    hanggliding BOOLEAN,
    paragliding BOOLEAN,
    suitability_hg TEXT,
    suitability_hg_en TEXT,
    suitability_pg TEXT,
    suitability_pg_en TEXT,
    location_remarks TEXT,
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7)
);